### ISSUE TITLE
Rollback to original firmware

### ISSUE THREAD

**Issue by shark526** [vorby01/ender-7_klipper_installation#1]
Hi Vorby01,
Thank you for share this klipper installer repo, this would helps a lot for us who have a ender 7 but want to try klipper.
Before I start try by following your instructions, I have a question: could I flash back the original official firmware after the klipper firmware installed? If yes, does it requires special method to rollback, or just us the normal upgrade instructions which provided on Creality site?
Thanks again!

**Comment by vorby01** [comment]
I havn't actually gone back to creality's firmware after installing the klipper firmware myself.
but it is just re-flashing the mainboard firmware, so if you wanted to yes it should just be a matter of following creality's upgrade instructions to restore the mainboard firmware.

**Comment by shark526** [comment]
Thank you for the confirmation. 😄
